/* CVS $Id: $ */
package net.interition.sparlycode.model; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /Users/pjworrall/Documents/Java2RDF/sparqlycode/sparqlycode-maven-plugin/src/main/resources/ISCO.ttl 
 * @author Auto-generated by schemagen on 08 Apr 2015 09:34 
 */
public class ISCO {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://ontology.interition.net/sparqlycode/vocabulary/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property cpeId = m_model.createProperty( "http://ontology.interition.net/sparqlycode/vocabulary/cpeId" );
    
    public static final Property file = m_model.createProperty( "http://ontology.interition.net/sparqlycode/vocabulary/file" );
    
    public static final Property fileLocation = m_model.createProperty( "http://ontology.interition.net/sparqlycode/vocabulary/fileLocation" );
    
    public static final Property fileName = m_model.createProperty( "http://ontology.interition.net/sparqlycode/vocabulary/fileName" );
    
    public static final Property fileSuffix = m_model.createProperty( "http://ontology.interition.net/sparqlycode/vocabulary/fileSuffix" );
    
    public static final Property fullFileName = m_model.createProperty( "http://ontology.interition.net/sparqlycode/vocabulary/fullFileName" );
    
    public static final Resource File = m_model.createResource( "http://ontology.interition.net/sparqlycode/vocabulary/File" );
    
    public static final Resource MavenProject = m_model.createResource( "http://ontology.interition.net/sparqlycode/vocabulary/MavenProject" );
    
}
